title: Site

fields:
  title:
    label: Title
    type:  text

  author:
    label: Author (meta)
    type:  text

  twitter:
    label: Twitter account
    type:  text
    help: include @, for example @CrossParallels

  description:
    label: Description (meta)
    type:  markdown

  copyright:
    label: Copyright
    type:  markdown
